### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by hershaw** [Daltix/snowconn#6]
Here is a gitlab circleci entry that releases to pypi

```
image: python:3.6

before_script:
   - pip install twine
   - python setup.py sdist

production:
  type: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=novamud --api-key=$HEROKU_PRODUCTION_API_KEY
    - twine upload dist/*
  only:
    - master
```

We should make a circleci one as well.
